### ISSUE TITLE
数据库加载不出来，指令无效

### ISSUE THREAD

**Issue by Katono5** [Ikaros-521/nonebot_plugin_abstain_diary#1]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/61302913/208924323-cced3df7-36c3-43ae-b8ad-70fb9b9ca92c.png">
数据库加载不出来，安装正常没有报错。
<img width="617" alt="image" src="https://user-images.githubusercontent.com/61302913/208925380-f3d0de66-4cce-450b-ac74-6163c485d069.png">
指令无效，机器人对指令没有反应

**Comment by Ikaros-521** [comment]
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/61302913/208924323-cced3df7-36c3-43ae-b8ad-70fb9b9ca92c.png">
> 
> 数据库加载不出来，安装正常没有报错。
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/61302913/208925380-f3d0de66-4cce-450b-ac74-6163c485d069.png">
> 
> 指令无效，机器人对指令没有反应

没有触发需要确认你的命令前缀是否是 /

**Comment by Ikaros-521** [comment]
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/61302913/208924323-cced3df7-36c3-43ae-b8ad-70fb9b9ca92c.png">
> 
> 数据库加载不出来，安装正常没有报错。
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/61302913/208925380-f3d0de66-4cce-450b-ac74-6163c485d069.png">
> 
> 指令无效，机器人对指令没有反应

需要将/ 替换成你现在使用的，一般可能是没有 或者是 # 这种

**Comment by Ikaros-521** [comment]
.env.xx里的 `COMMAND_START=["/", ""]  # 配置命令起始字符`

**Comment by Ikaros-521** [comment]
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/61302913/208924323-cced3df7-36c3-43ae-b8ad-70fb9b9ca92c.png">
> 
> 数据库加载不出来，安装正常没有报错。
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/61302913/208925380-f3d0de66-4cce-450b-ac74-6163c485d069.png">
> 
> 指令无效，机器人对指令没有反应

等等 你这是私聊呀，那没事了，私聊没有实现。

**Comment by Katono5** [comment]
私聊没实现啊，okayokay，麻烦说明了

**Comment by Ikaros-521** [comment]
> 私聊没实现啊，okayokay，麻烦说明了

因为私聊打卡没有啥必要 就没做。 自行打卡的话 随便自己发个数字记录下就可以了，做到bot感觉有点多此一举了
