### ISSUE TITLE
自定义 戒的内容

### ISSUE THREAD

**Issue by kongxiangyi88** [Ikaros-521/nonebot_plugin_abstain_diary#2]
希望能自定义目标，比如戒抽卡，戒奶茶等等，以戒开头，群友都可以自定义

**Comment by Ikaros-521** [comment]
可以考虑实现 考虑方案中

**Comment by Ikaros-521** [comment]
> 希望能自定义目标，比如戒抽卡，戒奶茶等等，以戒开头，群友都可以自定义

**v0.1.0** 针对需求点重构项目，命令全部推翻，用户可以自定义戒的内容。
可以使用 `nb plugin update nonebot_plugin_abstain_diary` 命令升级插件

需要注意 由于数据结构发生变化，需要删除旧数据或进行旧数据的改造后才能进行数据迁移。  
数据文件位于bot根目录的`data/abstain_diary/data.json`文件中  
如果没有需要备份的数据，请直接删除数据文件，重启nb即可重新生成。
如果需要备份的话，可以参考数据格式  
将旧的
```
{
    group_id: {
        user_id: {
            "tgt_days": tgt_days,
            "now_days": 1,
            "nickname": nickname,
            "last_time" : now_time
        }
    }
}
```
改为（其中content改为 `"色"`，然后将其中的内容用{}组回json串，请务必确保json串格式正确，否则程序无法解析）
```
{
    group_id: {
        content: {
            user_id: {
                "tgt_days": tgt_days,
                "now_days": 1,
                "nickname": nickname,
                "last_time" : now_time
            }
        }
    }
}
```
在线json串校验：[https://www.sojson.com/](https://www.sojson.com/)
